AWSTemplateFormatVersion: "2010-09-09"
Description: "Album stack template"
Parameters:
  Env:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - prod
  Priority:
    Type: Number
    Default: 3654
  Service:
    Type: String
    Default: 'album'
  VpcId:
    Type: String
    Default: 'vpc-0c0e5846b5f2992b5'
  Version:
    Type: String
    Default: '4.0.0'
  Prefix:
    Type: String
    Default: 'AM'
Resources:
  Inventory:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [ "https://bts-deployments.s3.amazonaws.com/cloudformation/inventory/", !Ref Env, "/inventory.yaml" ] ]
      Parameters:
        Env: !Ref Env
        Priority: !Ref Priority
        VpcId: !Ref VpcId
        Version: !Ref Version
        Service: !Ref Service
        Prefix: !Ref Prefix
  TrackClient:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [ "https://bts-deployments.s3.amazonaws.com/cloudformation/track/", !Ref Env, "/client.yaml" ] ]
      Parameters:
        Env: !Ref Env
        Service: !Join [ '-', [ 'inventory', !Ref Service ] ]
  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
        - '-'
        - - !Ref Env
          - 'inventory'
          - !Ref Service
          - 'item'
      BillingMode: PAY_PER_REQUEST